# -- Main Menu --

[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "班级介绍"
  pageRef = "about"
  weight = 20

[[main]]
  name = "成员名单"
  pageRef = "members"
  weight = 25

[[main]]
  name = "作业公示"
  pageRef = "homework"
  weight = 30

[[main]]
  name = "大事公示"
  pageRef = "events"
  weight = 35

[[main]]
  name = "班级动态"
  pageRef = "posts"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "班级介绍"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "成员名单"
  pageRef = "members"
  weight = 15

[[footer]]
  name = "作业公示"
  pageRef = "homework"
  weight = 20

[[footer]]
  name = "大事公示"
  pageRef = "events"
  weight = 25
